default: &default
  adapter:  postgresql
  host:     localhost
  username: markstephenson
  password:

development:
  <<: *default
  database: levelup-dev

test:
  <<: *default
  database: levelup-test
